using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.0
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.TestDatabaseSetup")]
[assembly: AssemblyDescriptionAttribute("Test Database Setup for NHibernate.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.TestDatabaseSetup")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("4.0.0.4000")]
[assembly: AssemblyInformationalVersionAttribute("4.0.2.GA")]
[assembly: AssemblyFileVersionAttribute("4.0.2.4000")]
[assembly: AssemblyDelaySignAttribute(false)]

